version: '3'
services:
  pep8speaks:
    build: .
    image: pep8speaks
    ports:
      - ${SERVICE_PORT-8000}:8000
    command: [ "gunicorn", "server:app", "--bind", "0.0.0.0:8000", "--workers", "4" ]
    environment:
      APP_SECRET_KEY: ${APP_SECRET_KEY-secret_key}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_APP_WEBHOOK_SECRET: ${GITHUB_APP_WEBHOOK_SECRET}
      LOG_LEVEL: ${LOG_LEVEL-DEBUG}
      FLASK_DEBUG: ${FLASK_DEBUG-1}
      BOT_USERNAME: ${BOT_USERNAME-pep8speaks}
    restart: always
